modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="compote" #mandatory
version="1.1.0" #mandatory
displayName="Compote" #mandatory
authors="thenatekirby" #optional
description='''
QOL improvements to the composter
'''

[[dependencies.compote]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.compote]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.compote]]
    modId="babel"
    mandatory=true
    versionRange="[3.0.0,4.0.0)"
    ordering="AFTER"
    side="BOTH"
